[paths]
tools_dir = "tools"
testcase_input_dir = "in"
testcase_output_dir = "out"
optuna_work_dir = "optuna_work"

[files]
cpp_file = "main.cpp"
combined_file = "combined.cpp"
sol_file = "solution"
gen_file = "gen"
vis_file = "vis"
tester_file = "tester"
optuna_db_file = "optuna_study.db"
optuna_params_file = "params.json"

[problem]
pretest_count = 150
interactive = false
objective = "minimize"
score_prefix = "Score ="

